[package]
name = "fe-new-codegen"
version = "0.1.0"
edition.workspace = true

[dependencies]
driver = { path = "../driver", package = "fe-driver" }
mir = { path = "../mir", package = "fe-mir" }
hir.workspace = true
hex = "0.4"
